# Based on appveyor.yml of ripgrep and
# https://github.com/starkat99/appveyor-rust
os: Visual Studio 2015

environment:
  matrix:
  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Stable 32-bit MSVC
    - channel: stable
      target: i686-pc-windows-msvc
  # Stable 64-bit GNU
    - channel: stable
      target: x86_64-pc-windows-gnu
  # Stable 32-bit GNU
    - channel: stable
      target: i686-pc-windows-gnu

## Install Script ##
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

## Build Script ##
build: false

test_script: cargo test --verbose %cargoflags%

before_deploy:
  # Generate artifacts for release
  - cargo build --release
  - mkdir staging
  - copy target\release\rnr.exe staging
  - ps: copy target\release\build\rnr-*\out\_rnr.ps1 staging
  - copy README.md staging
  - copy LICENSE staging
  - cd staging
  - 7z a ../rnr-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../rnr-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: 'Automated release'
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  auth_token:
    secure: Tz4TKacVOJpbdd6rJ/MsgYAR/vr/OkbafruG3yAQA5nymwBoenVPMowjRRS0g3WW
  provider: GitHub
  # deploy when a new tag is pushed and only on the stable channel
  on:
    # channel to use to produce the release artifacts
    CHANNEL: stable
    appveyor_repo_tag: true

matrix:
  fast_finish: true
