[package]
name = "rnr"
version = "0.1.6"
authors = ["Ismael González Valverde <ismgonval@gmail.com>"]
description = "rnr is a command-line tool to batch rename files and directories"
categories = ["command-line-utilities"]
license = "MIT"
homepage = "https://github.com/ChuckDaniels87/rnr"
repository = "https://github.com/ChuckDaniels87/rnr"
build = "build.rs"
readme = "README.md"

[dependencies]
ansi_term = "0.11"
atty = "0.2"
clap = "~2.32"
path_abs = "0.4"
regex = "1"
tempfile = "3"
walkdir= "2"

[build-dependencies]
clap = "~2.32"

[badges]
travis-ci = { repository = "ChuckDaniels87/rnr", branch = "master" }
appveyor = { repository = "ChuckDaniels87/rnr", branch = "master" }
