[package]
name = "rnr"
version = "0.1.0"
authors = ["Ismael González Valverde <ismgonval@gmail.com>"]
description = "rnr is a command-line tool to batch rename files for ANSI terminals"
license = "MIT"

[dependencies]
ansi_term = "0.11"
clap = "~2.32"
regex = "1"
walkdir= "2"
tempfile = "3"
